### ISSUE TITLE
Implement user defined history

### ISSUE THREAD

**Issue by calumy** [MarcoFossati/projects-cluster#55]
Allow the user to choose how many levels of history are used to calculate the mesh for the next iteration. 

 - [x] Add feature to allow user to choose history level (historyLevel variavle)
 - [x] Check for historyLevel = 0
 - [x] Check for historyLevel = 1
 - [x] Check for historyLevel = 2

All above checks will be run on RAE2822 example for 5 iterations (Run 0 to Run 4).

**Comment by CalumY** [comment]
Script modified to allow the user to set the history level. This was done by changing the way that the '.geo' file was defined so that the previous file was not merged. Instead, all the required components from the previous iterations were merged. 

Tested for history level 2:

Mesh
Run 0:
![image](https://user-images.githubusercontent.com/32770960/33074876-9e7f6a50-cebf-11e7-96c9-de959e9a04d0.png)

Run 1:
![image](https://user-images.githubusercontent.com/32770960/33074887-ad55dd2a-cebf-11e7-8c30-4e101ef0c553.png)

Run 2: 
![image](https://user-images.githubusercontent.com/32770960/33074915-bd851274-cebf-11e7-8654-1ba7533252e5.png)
The mesh has become denser at the position of the two shocks from Run 0 and Run 1.

Run 3: 
![image](https://user-images.githubusercontent.com/32770960/33074944-d8226ffa-cebf-11e7-9a60-ffb7765a9877.png)
The position of the shock in Run 0 is now removed as there are only two levels of history involved. (Run 1 and Run 2). 

Run 4:
![image](https://user-images.githubusercontent.com/32770960/33074966-e841e078-cebf-11e7-9701-9c0eac2d4eaf.png)
There is very little mesh density at the shock position. Not sure why this is. Going to change the way that the '.pos' file is generated as there may be an issue there. The '.pos' file for Run 2 and 3 are almost identical so this might be why there is very little mesh density at shock location. 

Run 5:
![image](https://user-images.githubusercontent.com/32770960/33074999-0118104a-cec0-11e7-9b0a-0f4433578fb6.png)


Mach Gradient
Run 0:
![image](https://user-images.githubusercontent.com/32770960/33075050-280d70be-cec0-11e7-944c-ed1857dbf443.png)

Run 1:
![image](https://user-images.githubusercontent.com/32770960/33075062-3116c96c-cec0-11e7-894e-544cbf774940.png)

Run 2: 
![image](https://user-images.githubusercontent.com/32770960/33075072-3f531dfa-cec0-11e7-810c-93828b2d135c.png)

Run 3: 
![image](https://user-images.githubusercontent.com/32770960/33075088-4f0707b6-cec0-11e7-954e-6791c7868a2c.png)

Run 4:
![image](https://user-images.githubusercontent.com/32770960/33075104-58783946-cec0-11e7-893d-8e6b220618b8.png)

Pressure Gradient
Run 0:
![image](https://user-images.githubusercontent.com/32770960/33075138-6becd4a0-cec0-11e7-8283-7c61ce4f6bb3.png)

Run 1:
![image](https://user-images.githubusercontent.com/32770960/33075152-762768a4-cec0-11e7-8c54-1837050f0bb3.png)

Run 2: 
![image](https://user-images.githubusercontent.com/32770960/33075164-801be83a-cec0-11e7-964f-c09540710d07.png)

Run 3: 
![image](https://user-images.githubusercontent.com/32770960/33075185-8bad97c0-cec0-11e7-8858-643bec6c9a10.png)

Run 4:
![image](https://user-images.githubusercontent.com/32770960/33075189-8ea0e2d4-cec0-11e7-9a76-267d0b0cdf01.png)

Mach Field
Run 0:
![image](https://user-images.githubusercontent.com/32770960/33075252-c6b07b9e-cec0-11e7-8c6b-f17d64af091d.png)

Run 1:
![image](https://user-images.githubusercontent.com/32770960/33075269-d12c82f2-cec0-11e7-9ccf-848c90eaa3df.png)

Run 2: 
![image](https://user-images.githubusercontent.com/32770960/33075290-dd7c9ce0-cec0-11e7-88b4-1548773f9b33.png)

Run 3: 
![image](https://user-images.githubusercontent.com/32770960/33075307-eb079950-cec0-11e7-9b31-ce01ee7ffd4c.png)

Run 4:
![image](https://user-images.githubusercontent.com/32770960/33075318-f4b5759e-cec0-11e7-9596-79525e44847d.png)

**Comment by CalumY** [comment]
Changed the way that the '.pos' files are created by creating a '.geo' file with the full history to see if this changed the density of mesh on Run 4. 

Tested for history level 2:

Mesh
Run 0:
![image](https://user-images.githubusercontent.com/32770960/33075911-f4000b80-cec2-11e7-87c5-5028adfa635d.png)
Very similar to the old method.

Run 1:
![image](https://user-images.githubusercontent.com/32770960/33075934-06b5bd4c-cec3-11e7-8154-7ae9dc4678c1.png)
Very similar to the old method.

Run 2:
![image](https://user-images.githubusercontent.com/32770960/33075950-143c2ff0-cec3-11e7-98cf-0c55c6bee381.png)
Very similar to the old method.

Run 3:
![image](https://user-images.githubusercontent.com/32770960/33075965-27e0577a-cec3-11e7-9689-df08011fc9c7.png)
Very similar to the old method.

Run 4:
![image](https://user-images.githubusercontent.com/32770960/33076002-431b8f64-cec3-11e7-9f08-1a52076aaa23.png)
Slightly denser mesh than old method around shock position. '.pos' file is slightly different between Run 2 and Run 3. 

Mach Gradient
Run 0:
![image](https://user-images.githubusercontent.com/32770960/33076161-dd1e7a36-cec3-11e7-9c1f-a820cd7aa30d.png)

Run 1:
![image](https://user-images.githubusercontent.com/32770960/33076177-e8cf19da-cec3-11e7-843b-711b4a36d415.png)

Run 2:
![image](https://user-images.githubusercontent.com/32770960/33076187-f2f4520e-cec3-11e7-9c66-a92500ed06cf.png)

Run 3:
![image](https://user-images.githubusercontent.com/32770960/33076205-fdd8477a-cec3-11e7-869f-5e2b2544f4e1.png)

Run 4:
![image](https://user-images.githubusercontent.com/32770960/33076219-0d086036-cec4-11e7-9f1d-b511e6cc95c8.png)

Pressure Gradient
Run 0:
![image](https://user-images.githubusercontent.com/32770960/33076352-756b5f98-cec4-11e7-9d49-bc5bc642df80.png)

Run 1:
![image](https://user-images.githubusercontent.com/32770960/33076387-84913d44-cec4-11e7-9682-313b75950b02.png)

Run 2:
![image](https://user-images.githubusercontent.com/32770960/33076408-8edd765a-cec4-11e7-87c6-2e465698af9c.png)

Run 3:
![image](https://user-images.githubusercontent.com/32770960/33076435-a1a1b030-cec4-11e7-9f29-3121c1778beb.png)

Run 4:
![image](https://user-images.githubusercontent.com/32770960/33076452-ab73a67c-cec4-11e7-80b4-ebe050750ff4.png)

Mach Field
Run 0:
![image](https://user-images.githubusercontent.com/32770960/33076482-c2ecc0cc-cec4-11e7-9821-de7dcd4cb0b7.png)

Run 1:
![image](https://user-images.githubusercontent.com/32770960/33076507-cc52bcd4-cec4-11e7-8156-55fa4d22f87c.png)

Run 2:
![image](https://user-images.githubusercontent.com/32770960/33076516-d6d9cab2-cec4-11e7-9b4f-a32f69156d37.png)

Run 3:
![image](https://user-images.githubusercontent.com/32770960/33076535-e0b2f07c-cec4-11e7-8b30-71d2f456700d.png)

Run 4:
![image](https://user-images.githubusercontent.com/32770960/33076548-ec37e86c-cec4-11e7-88ae-12a1ce8e38ac.png)

**Comment by CalumY** [comment]
Level of History = Full History
Meshes:
Run 0:
Full History Method:
![image](https://user-images.githubusercontent.com/32770960/33168548-3a0e8e9a-d039-11e7-8501-20c84c0c2b51.png)

Partial History Method:
![image](https://user-images.githubusercontent.com/32770960/33170340-eb14eae4-d03f-11e7-8c44-0f1ac7c963dc.png)

Run 1: 
Full History Method:
![image](https://user-images.githubusercontent.com/32770960/33168591-608938ae-d039-11e7-816b-39c5d0963d99.png)

Partial History Method:
![image](https://user-images.githubusercontent.com/32770960/33170367-fcffe510-d03f-11e7-83b1-5cb7baa21308.png)

Run 2:
Full History Method:
![image](https://user-images.githubusercontent.com/32770960/33168616-70b18b1e-d039-11e7-82ef-2a05736400c3.png)

Partial History Method:
![image](https://user-images.githubusercontent.com/32770960/33170385-0cc18e40-d040-11e7-965b-4380a4279912.png)

Run 3:
Full History Method:
![image](https://user-images.githubusercontent.com/32770960/33168636-82057628-d039-11e7-90f6-40e864c7ea1c.png)

Partial History Method:
![image](https://user-images.githubusercontent.com/32770960/33170406-1c9fb22e-d040-11e7-9d04-009c14298fa5.png)

Run 4:
Full History Method:
![image](https://user-images.githubusercontent.com/32770960/33168656-94801290-d039-11e7-964f-df287b3e72f2.png)

Partial History Method:
![image](https://user-images.githubusercontent.com/32770960/33170437-2fa5c61a-d040-11e7-8e44-07e51991e98b.png)

Both versions of the script produce similar meshes for all runs.


Level of History = 1
Meshes:
Run 0:
Full History Method:
![image](https://user-images.githubusercontent.com/32770960/33169475-c113eb58-d03c-11e7-8525-9926a3880308.png)

Partial History Method:
![image](https://user-images.githubusercontent.com/32770960/33170503-5c8ee06c-d040-11e7-9b0b-76e1009f4d59.png)

Run 1: 
Full History Method:
![image](https://user-images.githubusercontent.com/32770960/33169497-d794dfae-d03c-11e7-99a5-a22a64f51394.png)

Partial History Method:
![image](https://user-images.githubusercontent.com/32770960/33170522-71ddc398-d040-11e7-8807-70c1016d2f1a.png)

Run 2:
Full History Method:
![image](https://user-images.githubusercontent.com/32770960/33169518-ea5a6b7c-d03c-11e7-8178-dab5345c295c.png)

Partial History Method:
![image](https://user-images.githubusercontent.com/32770960/33170545-880137ea-d040-11e7-84ce-9c7a11ddf3bc.png)

Run 3:
Full History Method:
![image](https://user-images.githubusercontent.com/32770960/33169546-fdecaea2-d03c-11e7-9dd3-bb910f9e8b89.png)

Partial History Method:
![image](https://user-images.githubusercontent.com/32770960/33170573-9c2866bc-d040-11e7-80f1-29ca2a6b301c.png)

Run 4:
Full History Method:
![image](https://user-images.githubusercontent.com/32770960/33169563-0d8dcef4-d03d-11e7-85ea-cd802ee8c68a.png)

Partial History Method:
![image](https://user-images.githubusercontent.com/32770960/33170594-ae58225a-d040-11e7-86e8-3df331fa4204.png)

Partial history method appears to create the same mesh for all iterations which is not the expected result.  Full history method produces an unexpected mesh for Run 3, there should be more mesh density around the shock position.


Level of History = 2
Meshes:
Run 0:
Full History Method:
![image](https://user-images.githubusercontent.com/32770960/33169627-3ed340f2-d03d-11e7-8da0-99cd3e8703ee.png)

Partial History Method:
![image](https://user-images.githubusercontent.com/32770960/33170650-f7ac9120-d040-11e7-9c6e-443009c51aae.png)

Run 1: 
Full History Method:
![image](https://user-images.githubusercontent.com/32770960/33169651-51bace7e-d03d-11e7-8126-1368a16131da.png)

Partial History Method:
![image](https://user-images.githubusercontent.com/32770960/33170665-0d457f42-d041-11e7-838f-c27e378fc85b.png)

Run 2:
Full History Method:
![image](https://user-images.githubusercontent.com/32770960/33169671-65f24d7c-d03d-11e7-8c55-f5f339bcbf2f.png)

Partial History Method:
![image](https://user-images.githubusercontent.com/32770960/33170678-1c4a2952-d041-11e7-8cf6-aec8594004e2.png)

Run 3:
Full History Method:
![image](https://user-images.githubusercontent.com/32770960/33169697-767254a8-d03d-11e7-81d2-6f0e908d72a4.png)

Partial History Method:
![image](https://user-images.githubusercontent.com/32770960/33170704-2fb15c18-d041-11e7-80db-07a6eaec1689.png)

Run 4:
Full History Method:
![image](https://user-images.githubusercontent.com/32770960/33169710-85b6b51c-d03d-11e7-82d4-0746f57dc47a.png)

Partial History Method:
![image](https://user-images.githubusercontent.com/32770960/33170718-3ff7a80c-d041-11e7-808d-8e86047f2790.png)

Both scripts produce similar results up until run 3, however the mesh created for run 4 is odd as there is very little mesh density around the shock position.

**Comment by CalumY** [comment]
The issue that produced the same meshes for every iteration with one level of history was fixed and the following results produced:

Level of History = Full History
Meshes:
Run 0:
![image](https://user-images.githubusercontent.com/32770960/33234421-6d63d886-d21e-11e7-8a17-f7b6216d66c5.png)

Run 1:
![image](https://user-images.githubusercontent.com/32770960/33234425-812d540a-d21e-11e7-9057-9199ea9487e4.png)

Run 2: 
![image](https://user-images.githubusercontent.com/32770960/33234428-8f679148-d21e-11e7-88d2-78c569e704e0.png)

Run 3:
![image](https://user-images.githubusercontent.com/32770960/33234437-b3cfe38c-d21e-11e7-9f90-c306e876ad1f.png)

Run 4: 
![image](https://user-images.githubusercontent.com/32770960/33234432-a46612e0-d21e-11e7-901a-8031131dd474.png)


Level of History = 1
Meshes:
Run 0:
![image](https://user-images.githubusercontent.com/32770960/33234440-c717d7ba-d21e-11e7-96c7-6a3bcfe51882.png)

Run 1:
![image](https://user-images.githubusercontent.com/32770960/33234442-d754af7c-d21e-11e7-8fad-addb262347c4.png)

Run 2: 
![image](https://user-images.githubusercontent.com/32770960/33234443-e8903aae-d21e-11e7-8d1b-4f1dbc0a6d7e.png)

Run 3:
![image](https://user-images.githubusercontent.com/32770960/33234448-f903a740-d21e-11e7-8df0-7fe73bd402f2.png)

Run 4: 
![image](https://user-images.githubusercontent.com/32770960/33234457-15516176-d21f-11e7-96b6-3d5430b0100b.png)


Level of History = 2
Meshes:
Run 0:
![image](https://user-images.githubusercontent.com/32770960/33234467-2b2ba722-d21f-11e7-8faa-98d2351237cb.png)

Run 1:
![image](https://user-images.githubusercontent.com/32770960/33234472-3c7a39a8-d21f-11e7-9b47-e1a336f21bc3.png)

Run 2: 
![image](https://user-images.githubusercontent.com/32770960/33234477-4f74235c-d21f-11e7-9964-48e21777f870.png)

Run 3:
![image](https://user-images.githubusercontent.com/32770960/33234482-5e4f0180-d21f-11e7-9824-f435073089cd.png)

Run 4: 
![image](https://user-images.githubusercontent.com/32770960/33234489-6d2beb1e-d21f-11e7-93a9-5dc1129d925a.png)

**Comment by CalumY** [comment]
The issue that causes the mesh density to reduce appears to be when the mach and pressure gradient are very high e.g. when the mesh is dense.

**Comment by CalumY** [comment]
Variable added to set level where full history starts again. This will be useful as it will allow the script to get rid of the poor simulations (usually the first one) before refining it more. This also solves the issue where the mesh density reduces around the shock position.

In future, this could be used with error estimators to go back and include more levels of history if the quality of the simulation decreases from one iteration to the next. 

Partial history method will be used from now on as it produces fewer files and uses less code to run to produce the same result. 

The simulation was run again:

Level of History = Full History
Full History Restart Level = 3 (Doesn't matter for this simulation as the full history is always included)
Meshes:
Run 0:
![image](https://user-images.githubusercontent.com/32770960/33263806-14d375fa-d363-11e7-822c-184d9770b679.png)

Run 1:
![image](https://user-images.githubusercontent.com/32770960/33263826-24e16862-d363-11e7-8627-e5dc9aa95ee2.png)

Run 2:
![image](https://user-images.githubusercontent.com/32770960/33263841-37a46eea-d363-11e7-83c1-ef28848fb4fb.png)

Run 3:
![image](https://user-images.githubusercontent.com/32770960/33263855-4a1dd750-d363-11e7-8ecd-2595e030b205.png)

Run 4:
![image](https://user-images.githubusercontent.com/32770960/33263872-5d678b08-d363-11e7-85c9-cf64cdf3382a.png)


Level of History = 1
Full History Restart Level = 3 (Two greater than the level of history as this allows the first iteration to be discarded as they are usually poor simulations.)
Meshes:
Run 0:
![image](https://user-images.githubusercontent.com/32770960/33263905-7b6ed476-d363-11e7-84a7-38574765d592.png)

Run 1:
![image](https://user-images.githubusercontent.com/32770960/33263928-8a67f9c6-d363-11e7-93b2-a515938b8cce.png)

Run 2:
![image](https://user-images.githubusercontent.com/32770960/33263950-99086d30-d363-11e7-97a4-177a12c92e96.png)

Run 3:
![image](https://user-images.githubusercontent.com/32770960/33263970-a9f07534-d363-11e7-8448-670f8d7d62f5.png)

Run 4:
![image](https://user-images.githubusercontent.com/32770960/33264001-b96153c6-d363-11e7-9299-029819a04536.png)


Level of History = 2
Full History Restart Level = 4 (Two greater than the level of history as this allows the first iteration to be discarded as they are usually poor simulations.)
Meshes:
Run 0:
![image](https://user-images.githubusercontent.com/32770960/33264107-21bf25e2-d364-11e7-9e4e-4c0966dc24c0.png)

Run 1:
![image](https://user-images.githubusercontent.com/32770960/33264128-361ef454-d364-11e7-9099-9ad0b361831b.png)

Run 2:
![image](https://user-images.githubusercontent.com/32770960/33264147-466f3922-d364-11e7-9305-a414779a1ff9.png)

Run 3:
![image](https://user-images.githubusercontent.com/32770960/33264168-58a39106-d364-11e7-8523-0e5686ded1a4.png)

Run 4:
![image](https://user-images.githubusercontent.com/32770960/33264186-6b7ab3fe-d364-11e7-896f-9744616b4c54.png)
